// countryCodeMap.ts
// Mapping complet des pays vers leurs codes de drapeaux ISO

export const countryCodeMap: Record<string, string> = {
  // === Europe ===
  'Albania': 'al',
  'Andorra': 'ad',
  'Armenia': 'am',
  'Austria': 'at',
  'Azerbaijan': 'az',
  'Belarus': 'by',
  'Belgium': 'be',
  'Bosnia and Herzegovina': 'ba',
  'Bulgaria': 'bg',
  'Croatia': 'hr',
  'Cyprus': 'cy',
  'Czech Republic': 'cz',
  'Czechia': 'cz',
  'Denmark': 'dk',
  'England': 'gb-eng',
  'Estonia': 'ee',
  'Finland': 'fi',
  'France': 'fr',
  'Georgia': 'ge',
  'Germany': 'de',
  'Greece': 'gr',
  'Hungary': 'hu',
  'Iceland': 'is',
  'Ireland': 'ie',
  'Italy': 'it',
  'Kazakhstan': 'kz',
  'Kosovo': 'xk',
  'Latvia': 'lv',
  'Lithuania': 'lt',
  'Luxembourg': 'lu',
  'Malta': 'mt',
  'Moldova': 'md',
  'Monaco': 'mc',
  'Montenegro': 'me',
  'Netherlands': 'nl',
  'North Macedonia': 'mk',
  'Northern Ireland': 'gb-nir',
  'Norway': 'no',
  'Poland': 'pl',
  'Portugal': 'pt',
  'Romania': 'ro',
  'Russia': 'ru',
  'San Marino': 'sm',
  'Scotland': 'gb-sct',
  'Serbia': 'rs',
  'Slovakia': 'sk',
  'Slovenia': 'si',
  'Spain': 'es',
  'Sweden': 'se',
  'Switzerland': 'ch',
  'Turkey': 'tr',
  'Ukraine': 'ua',
  'Wales': 'gb-wls',

  // === Amérique du Sud ===
  'Argentina': 'ar',
  'Bolivia': 'bo',
  'Brazil': 'br',
  'Chile': 'cl',
  'Colombia': 'co',
  'Ecuador': 'ec',
  'Paraguay': 'py',
  'Peru': 'pe',
  'Uruguay': 'uy',
  'Venezuela': 've',

  // === Amérique du Nord et Centrale ===
  'Canada': 'ca',
  'Costa Rica': 'cr',
  'El Salvador': 'sv',
  'Guatemala': 'gt',
  'Honduras': 'hn',
  'Jamaica': 'jm',
  'Mexico': 'mx',
  'Nicaragua': 'ni',
  'Panama': 'pa',
  'Trinidad and Tobago': 'tt',
  'United States': 'us',
  'USA': 'us',

  // === Afrique ===
  'Algeria': 'dz',
  'Angola': 'ao',
  'Benin': 'bj',
  'Burkina Faso': 'bf',
  'Burundi': 'bi',
  'Cameroon': 'cm',
  'Cape Verde': 'cv',
  'Central African Republic': 'cf',
  'Chad': 'td',
  'Comoros': 'km',
  'Congo': 'cg',
  'DR Congo': 'cd',
  'Democratic Republic of the Congo': 'cd',
  'Djibouti': 'dj',
  'Egypt': 'eg',
  'Equatorial Guinea': 'gq',
  'Eritrea': 'er',
  'Ethiopia': 'et',
  'Gabon': 'ga',
  'Gambia': 'gm',
  'Ghana': 'gh',
  'Guinea': 'gn',
  'Guinea-Bissau': 'gw',
  'Ivory Coast': 'ci',
  'Kenya': 'ke',
  'Lesotho': 'ls',
  'Liberia': 'lr',
  'Libya': 'ly',
  'Madagascar': 'mg',
  'Malawi': 'mw',
  'Mali': 'ml',
  'Mauritania': 'mr',
  'Mauritius': 'mu',
  'Morocco': 'ma',
  'Mozambique': 'mz',
  'Namibia': 'na',
  'Niger': 'ne',
  'Nigeria': 'ng',
  'Rwanda': 'rw',
  'Senegal': 'sn',
  'Sierra Leone': 'sl',
  'Somalia': 'so',
  'South Africa': 'za',
  'South Sudan': 'ss',
  'Sudan': 'sd',
  'Tanzania': 'tz',
  'Togo': 'tg',
  'Tunisia': 'tn',
  'Uganda': 'ug',
  'Zambia': 'zm',
  'Zimbabwe': 'zw',

  // === Asie ===
  'Afghanistan': 'af',
  'Bahrain': 'bh',
  'Bangladesh': 'bd',
  'Bhutan': 'bt',
  'Brunei': 'bn',
  'Cambodia': 'kh',
  'China': 'cn',
  'Hong Kong': 'hk',
  'India': 'in',
  'Indonesia': 'id',
  'Iran': 'ir',
  'Iraq': 'iq',
  'Israel': 'il',
  'Japan': 'jp',
  'Jordan': 'jo',
  'Kuwait': 'kw',
  'Kyrgyzstan': 'kg',
  'Laos': 'la',
  'Lebanon': 'lb',
  'Malaysia': 'my',
  'Maldives': 'mv',
  'Mongolia': 'mn',
  'Myanmar': 'mm',
  'Nepal': 'np',
  'North Korea': 'kp',
  'Oman': 'om',
  'Pakistan': 'pk',
  'Palestine': 'ps',
  'Philippines': 'ph',
  'Qatar': 'qa',
  'Saudi Arabia': 'sa',
  'Singapore': 'sg',
  'South Korea': 'kr',
  'Sri Lanka': 'lk',
  'Syria': 'sy',
  'Taiwan': 'tw',
  'Tajikistan': 'tj',
  'Thailand': 'th',
  'Timor-Leste': 'tl',
  'Turkmenistan': 'tm',
  'United Arab Emirates': 'ae',
  'UAE': 'ae',
  'Uzbekistan': 'uz',
  'Vietnam': 'vn',
  'Yemen': 'ye',

  // === Océanie ===
  'Australia': 'au',
  'Fiji': 'fj',
  'New Zealand': 'nz',
  'Papua New Guinea': 'pg',
  'Samoa': 'ws',
  'Solomon Islands': 'sb',
  'Tonga': 'to',
  'Vanuatu': 'vu',

  // === Caraïbes ===
  'Antigua and Barbuda': 'ag',
  'Bahamas': 'bs',
  'Barbados': 'bb',
  'Belize': 'bz',
  'Bermuda': 'bm',
  'Cuba': 'cu',
  'Curaçao': 'cw',
  'Dominica': 'dm',
  'Dominican Republic': 'do',
  'Grenada': 'gd',
  'Guadeloupe': 'gp',
  'Guyana': 'gy',
  'Haiti': 'ht',
  'Martinique': 'mq',
  'Puerto Rico': 'pr',
  'Saint Kitts and Nevis': 'kn',
  'Saint Lucia': 'lc',
  'Saint Vincent and the Grenadines': 'vc',
  'Suriname': 'sr',
}

// Fonction helper pour obtenir le code du pays
export const getCountryCode = (nationality: string): string | null => {
  return countryCodeMap[nationality] || null
}

// Liste de tous les pays disponibles (utile pour l'autocomplétion)
export const availableCountries = Object.keys(countryCodeMap).sort()

// Nombre total de pays supportés
export const totalCountriesSupported = availableCountries.length